export const tweetsData = [
    {
        name: 'Manuel Banchero',
        handle: '@manu_banchero',
        profilePic: 'images/manu-banchero.jpg',
        tweetedDate: '2/21/20',
        tweetedAt: '09:28',
        tweetedFrom: 'Twitter Web App',
        likes: 461,
        retweets: 114,
        tweetText: 'UXR/UX: You can only bring one item to a remote island to assist your research of native use of tools and usability. What do you bring? #TellMeAboutYou',
        isLiked: false,
        isRetweeted: false,
        uuid: '2264228b-f502-4777-9910-b066a8bb2c79',
        followingLikes: [{
            name: 'Fermin Mujica',
            handle: '@ferminmujica21'
        }, {
            name: 'Nacho Sendoya',
            handle: '@supers'
        }],
        followingRetweet: [],
        isVerified: true,
        replies: [{
            name: 'Manuel Banchero',
            handle: '@manu_banchero',
            profilePic: 'images/manu-banchero.jpg',
            tweetedDate: '2/21/20',
            tweetedAt: '09:30',
            tweetedFrom: 'Twitter Web App',
            likes: 201,
            retweets: 39,
            tweetText: '~~ hiring for a UX Lead in Sydney - who should I talk to?',
            isLiked: false,
            isRetweeted: false,
            uuid: '2264228b-f502-4777-9910-b066a8bb2c78',
            isVerified: true,
            replies: []
        }]
    },
    {
        name: 'Fermin Mujica',
        handle: '@ferminmujica21',
        profilePic: 'images/EQFtEzJGERg-full.jpg',
        tweetedDate: '3/10/22',
        tweetedAt: '14:45',
        tweetedFrom: 'Twitter for iPhone',
        likes: 312,
        retweets: 89,
        tweetText: 'La clave del éxito en marketing digital no es solo captar clientes, sino fidelizarlos. 🚀',
        isLiked: false,
        isRetweeted: false,
        uuid: '3a1d2c4b-6f22-4938-a8d2-50c3b98bbdf1',
        followingLikes: [],
        followingRetweet: [{
            name: 'Nacho Sendoya',
            handle: '@supers'
        }],
        isVerified: false,
        replies: []
    },
    {
        name: 'Nacho Sendoya',
        handle: '@supers',
        profilePic: 'images/profile-picture.jpg',
        tweetedDate: '5/18/23',
        tweetedAt: '08:12',
        tweetedFrom: 'Twitter Web App',
        likes: 567,
        retweets: 213,
        tweetText: 'El crecimiento de una empresa depende más de las decisiones estratégicas que del esfuerzo. Tomar decisiones inteligentes es el verdadero reto. 💡',
        isLiked: false,
        isRetweeted: false,
        uuid: '7c2d3e4f-99ab-44de-b1fa-23d19f0cd6a8',
        followingLikes: [{
            name: 'Fermin Mujica',
            handle: '@ferminmujica21'
        }],
        followingRetweet: [],
        isVerified: false,
        replies: [
            {
                name: 'Manuel Banchero',
                handle: '@manu_banchero',
                profilePic: 'images/manu-banchero.jpg',
                tweetedDate: '5/18/23',
                tweetedAt: '08:20',
                tweetedFrom: 'Twitter Web App',
                likes: 78,
                retweets: 21,
                tweetText: 'Totalmente de acuerdo. A veces, un pequeño cambio estratégico puede marcar una gran diferencia. 🔥',
                isLiked: false,
                isRetweeted: false,
                uuid: 'f9a3b7c2-4b55-40cd-889f-23c1f1b1a3d9',
                isVerified: true,
                replies: []
            }
        ]
    },
    {
        name: 'Lucía Ortega',
        handle: '@luciaortega',
        profilePic: 'images/0fN7Fxv1eWA-full.jpg',
        tweetedDate: '7/02/24',
        tweetedAt: '17:30',
        tweetedFrom: 'Twitter for Android',
        likes: 245,
        retweets: 102,
        tweetText: 'La disciplina supera a la motivación. Si esperás a estar motivado para actuar, nunca vas a avanzar. 💯',
        isLiked: false,
        isRetweeted: false,
        uuid: 'a4d3f6b7-1c99-43e7-b2e8-d7f7c9c8a5f6',
        followingLikes: [{
            name: 'Manuel Banchero',
            handle: '@manu_banchero'
        }],
        followingRetweet: [],
        isVerified: true,
        replies: [
            {
                name: 'Fermin Mujica',
                handle: '@ferminmujica21',
                profilePic: '',
                tweetedDate: '7/02/24',
                tweetedAt: '17:45',
                tweetedFrom: 'Twitter for Android',
                likes: 50,
                retweets: 10,
                tweetText: 'Gran verdad. La clave es construir hábitos y sistemas en lugar de depender de la motivación. 💡',
                isLiked: false,
                isRetweeted: false,
                uuid: 'b6d7c9a2-5f33-48d2-b9e2-c1f4d6a3b8c5',
                isVerified: false,
                replies: []
            }
        ]
    },
    {
        name: 'Elon Musk',
        handle: '@elonmusk',
        profilePic: 'images/Elon-Musk.jpg',
        tweetedDate: '1/15/24',
        tweetedAt: '12:05',
        tweetedFrom: 'Twitter for iPhone',
        likes: 15230,
        retweets: 3401,
        tweetText: 'AI will change everything. The question is: will it be for better or worse?',
        isLiked: false,
        isRetweeted: false,
        uuid: 'e34b2f1a-76d9-4f50-91c2-83b6a8e3f5d2',
        followingLikes: [{ name: 'Bill Gates', handle: '@BillGates' }],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Cristiano Ronaldo',
        handle: '@Cristiano',
        profilePic: 'images/Cristiano-Ronaldo.avif',
        tweetedDate: '6/10/23',
        tweetedAt: '20:45',
        tweetedFrom: 'Twitter Web App',
        likes: 890231,
        retweets: 56200,
        tweetText: 'Hard work, dedication, and passion. Never stop pushing yourself. ⚽️🔥',
        isLiked: false,
        isRetweeted: false,
        uuid: 'f7c2a1d4-99ab-40cd-889f-23c1f1b1a3e8',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Taylor Swift',
        handle: '@taylorswift13',
        profilePic: 'images/Taylor-Swift.jpeg',
        tweetedDate: '4/20/24',
        tweetedAt: '15:30',
        tweetedFrom: 'Twitter for iPhone',
        likes: 750120,
        retweets: 112000,
        tweetText: 'So excited to announce the next leg of the Eras Tour! ✨💖',
        isLiked: false,
        isRetweeted: false,
        uuid: 'c8d4e6f2-5b33-48d2-b9e2-c1f4d6a3b8c7',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Bill Gates',
        handle: '@BillGates',
        profilePic: 'images/Bill-Gates.png',
        tweetedDate: '3/25/24',
        tweetedAt: '10:00',
        tweetedFrom: 'Twitter Web App',
        likes: 45200,
        retweets: 8700,
        tweetText: 'The world needs more innovative solutions to combat climate change. We have the technology. Now we need the commitment.',
        isLiked: false,
        isRetweeted: false,
        uuid: 'b3d7c9a2-5f33-48d2-b9e2-c1f4d6a3b8c5',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    }, 
    {
        name: 'Manuel Banchero',
        handle: '@manu_banchero',
        profilePic: 'images/manu-banchero.jpg',
        tweetedDate: '3/10/24',
        tweetedAt: '12:05',
        tweetedFrom: 'Twitter Web App',
        likes: 328,
        retweets: 85,
        tweetText: 'Si te enfocás en mejorar un 1% cada día, en un año serás 37 veces mejor. El progreso acumulativo es la clave. 📈',
        isLiked: false,
        isRetweeted: false,
        uuid: '5a6c3d9e-0b12-43f5-8d9e-bc74a6f5c2a1',
        followingLikes: [{ name: 'Lucía Ortega', handle: '@luciaortega' }],
        followingRetweet: [{ name: 'Nacho Sendoya', handle: '@supers' }],
        isVerified: true,
        replies: []
    },
    {
        name: 'Fermin Mujica',
        handle: '@ferminmujica21',
        profilePic: 'images/EQFtEzJGERg-full.jpg',
        tweetedDate: '3/15/24',
        tweetedAt: '19:30',
        tweetedFrom: 'Twitter for iPhone',
        likes: 412,
        retweets: 102,
        tweetText: 'El error más grande en los negocios: intentar venderle a todo el mundo. Encontrá tu nicho y dominá ese espacio. 🎯',
        isLiked: false,
        isRetweeted: false,
        uuid: 'c7d2a4f9-1b22-4e5a-b2d1-d8f9c7a4f8b3',
        followingLikes: [{ name: 'Manuel Banchero', handle: '@manu_banchero' }],
        followingRetweet: [],
        isVerified: false,
        replies: []
    },
    {
        name: 'Nacho Sendoya',
        handle: '@supers',
        profilePic: 'images/profile-picture.jpg',
        tweetedDate: '4/01/24',
        tweetedAt: '08:45',
        tweetedFrom: 'Twitter Web App',
        likes: 289,
        retweets: 91,
        tweetText: 'No esperes la oportunidad perfecta, creala. Cada decisión que tomás hoy define tu futuro. 🔥',
        isLiked: false,
        isRetweeted: false,
        uuid: 'f3d7e8b9-5c12-4a8e-b4f2-c8d9e7a6b3f4',
        followingLikes: [{ name: 'Lucía Ortega', handle: '@luciaortega' }],
        followingRetweet: [],
        isVerified: false,
        replies: [
            {
                name: 'Lucía Ortega',
                handle: '@luciaortega',
                profilePic: 'images/0fN7Fxv1eWA-full.jpg',
                tweetedDate: '4/01/24',
                tweetedAt: '09:00',
                tweetedFrom: 'Twitter for Android',
                likes: 76,
                retweets: 20,
                tweetText: 'Totalmente de acuerdo, Nacho. La acción siempre gana. 🚀',
                isLiked: false,
                isRetweeted: false,
                uuid: 'b4a3d7f2-9c11-41d9-a7f8-e2f5b8c4d7e3',
                isVerified: true,
                replies: []
            }
        ]
    },
    {
        name: 'Lucía Ortega',
        handle: '@luciaortega',
        profilePic: 'images/0fN7Fxv1eWA-full.jpg',
        tweetedDate: '4/10/24',
        tweetedAt: '16:20',
        tweetedFrom: 'Twitter for Android',
        likes: 512,
        retweets: 156,
        tweetText: 'No subestimes el poder de la constancia. El talento sin disciplina no sirve de nada. 🏆',
        isLiked: false,
        isRetweeted: false,
        uuid: 'd5f6b3a7-8c19-44e5-b2d4-f9c8a7e4b5c6',
        followingLikes: [{ name: 'Manuel Banchero', handle: '@manu_banchero' }],
        followingRetweet: [],
        isVerified: true,
        replies: [
            {
                name: 'Fermin Mujica',
                handle: '@ferminmujica21',
                profilePic: '',
                tweetedDate: '4/10/24',
                tweetedAt: '16:35',
                tweetedFrom: 'Twitter for iPhone',
                likes: 84,
                retweets: 25,
                tweetText: 'La constancia es lo que separa a los que sueñan de los que lo logran. 💡',
                isLiked: false,
                isRetweeted: false,
                uuid: 'e7b3a6f2-1c88-41d7-8d2f-f6c5b7a3d9e4',
                isVerified: false,
                replies: []
            }
        ]
    }
];