export const tweetsData = [
    {
        name: 'Manuel Banchero',
        handle: '@manu_banchero',
        profilePic: 'images/manu-banchero.jpg',
        tweetedDate: '2/21/20',
        tweetedAt: '09:28',
        tweetedFrom: 'Twitter Web App',
        likes: 461,
        retweets: 114,
        tweetText: 'UXR/UX: You can only bring one item to a remote island to assist your research of native use of tools and usability. What do you bring? #TellMeAboutYou',
        isLiked: false,
        isRetweeted: false,
        uuid: '2264228b-f502-4777-9910-b066a8bb2c79',
        followingLikes: [{
            name: 'Fermin Mujica',
            handle: '@ferminmujica21'
        }, {
            name: 'Nacho Sendoya',
            handle: '@supers'
        }],
        followingRetweet: [],
        isVerified: true,
        replies: [{
            name: 'Manuel Banchero',
            handle: '@manu_banchero',
            profilePic: 'images/manu-banchero.jpg',
            tweetedDate: '2/21/20',
            tweetedAt: '09:30',
            tweetedFrom: 'Twitter Web App',
            likes: 201,
            retweets: 39,
            tweetText: '~~ hiring for a UX Lead in Sydney - who should I talk to?',
            isLiked: false,
            isRetweeted: false,
            uuid: '2264228b-f502-4777-9910-b066a8bb2c78',
            isVerified: true,
            replies: []
        }]
    },
    {
        name: 'Fermin Mujica',
        handle: '@ferminmujica21',
        profilePic: 'images/EQFtEzJGERg-full.jpg',
        tweetedDate: '3/10/22',
        tweetedAt: '14:45',
        tweetedFrom: 'Twitter for iPhone',
        likes: 312,
        retweets: 89,
        tweetText: 'La clave del éxito en marketing digital no es solo captar clientes, sino fidelizarlos. 🚀',
        isLiked: false,
        isRetweeted: false,
        uuid: '3a1d2c4b-6f22-4938-a8d2-50c3b98bbdf1',
        followingLikes: [],
        followingRetweet: [{
            name: 'Nacho Sendoya',
            handle: '@supers'
        }],
        isVerified: false,
        replies: []
    },
    {
        name: 'Lucía Ortega',
        handle: '@luciaortega',
        profilePic: 'images/0fN7Fxv1eWA-full.jpg',
        tweetedDate: '7/02/24',
        tweetedAt: '17:30',
        tweetedFrom: 'Twitter for Android',
        likes: 245,
        retweets: 102,
        tweetText: 'La disciplina supera a la motivación. Si esperás a estar motivado para actuar, nunca vas a avanzar. 💯',
        isLiked: false,
        isRetweeted: false,
        uuid: 'a4d3f6b7-1c99-43e7-b2e8-d7f7c9c8a5f6',
        followingLikes: [{
            name: 'Manuel Banchero',
            handle: '@manu_banchero'
        }],
        followingRetweet: [],
        isVerified: true,
        replies: [
            {
                name: 'Fermin Mujica',
                handle: '@ferminmujica21',
                profilePic: '',
                tweetedDate: '7/02/24',
                tweetedAt: '17:45',
                tweetedFrom: 'Twitter for Android',
                likes: 50,
                retweets: 10,
                tweetText: 'Gran verdad. La clave es construir hábitos y sistemas en lugar de depender de la motivación. 💡',
                isLiked: false,
                isRetweeted: false,
                uuid: 'b6d7c9a2-5f33-48d2-b9e2-c1f4d6a3b8c5',
                isVerified: false,
                replies: []
            }
        ]
    },
    {
        name: 'Elon Musk',
        handle: '@elonmusk',
        profilePic: 'images/Elon-Musk.jpg',
        tweetedDate: '1/15/24',
        tweetedAt: '12:05',
        tweetedFrom: 'Twitter for iPhone',
        likes: 150230,
        retweets: 3401,
        tweetText: 'AI will change everything. The question is: will it be for better or worse?',
        isLiked: false,
        isRetweeted: false,
        uuid: 'e34b2f1a-76d9-4f50-91c2-83b6a8e3f5d2',
        followingLikes: [{ name: 'Bill Gates', handle: '@BillGates' }],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Cristiano Ronaldo',
        handle: '@Cristiano',
        profilePic: 'images/Cristiano-Ronaldo.avif',
        tweetedDate: '6/10/23',
        tweetedAt: '20:45',
        tweetedFrom: 'Twitter Web App',
        likes: 89999,
        retweets: 56200,
        tweetText: 'Hard work, dedication, and passion. Never stop pushing yourself. ⚽️🔥',
        isLiked: false,
        isRetweeted: false,
        uuid: 'f7c2a1d4-99ab-40cd-889f-23c1f1b1a3e8',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Taylor Swift',
        handle: '@taylorswift13',
        profilePic: 'images/Taylor-Swift.jpeg',
        tweetedDate: '4/20/24',
        tweetedAt: '15:30',
        tweetedFrom: 'Twitter for iPhone',
        likes: 1000000,
        retweets: 112000,
        tweetText: 'So excited to announce the next leg of the Eras Tour! ✨💖',
        isLiked: false,
        isRetweeted: false,
        uuid: 'c8d4e6f2-5b33-48d2-b9e2-c1f4d6a3b8c7',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    },
    {
        name: 'Bill Gates',
        handle: '@BillGates',
        profilePic: 'images/Bill-Gates.png',
        tweetedDate: '3/25/24',
        tweetedAt: '10:00',
        tweetedFrom: 'Twitter Web App',
        likes: 45200,
        retweets: 8700,
        tweetText: 'The world needs more innovative solutions to combat climate change. We have the technology. Now we need the commitment.',
        isLiked: false,
        isRetweeted: false,
        uuid: 'b3d7c9a2-5f33-48d2-b9e2-c1f4d6a3b8c5',
        followingLikes: [],
        followingRetweet: [],
        isVerified: true,
        replies: []
    }
];